apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: first-nextapp
  name: first-nextapp-svc
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: first-nextapp
  type: NodePort
status:
  loadBalancer: {}
