apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: first-nextapp
  name: first-nextapp-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: first-nextapp
  type: NodePort
status:
  loadBalancer: {}
