name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: "docker.io"
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}:$(date)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      uses: docker/login-action@v3.0.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ env.REGISTRY }} # optional
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }} # optional
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }} # optional
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: auto # optional, default is auto
        # Log out from the Docker registry at the end of a job
        logout: true # optional, default is true
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }} --target development

    - name: Push the Docker image
      run: docker push ${{ env.IMAGE_NAME }}
