name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: "docker.io"
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  VERSION: "v1.0.0"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build docker image
      uses: addnab/docker-run-action@v3
      with:
        image: docker:stable
        args: |
          build -t ${{ env.IMAGE_NAME }}:${{ env.VERSION }} .
    - name: push docker image
      uses: addnab/docker-run-action@v3
      with:
        image: docker:stable
        args: |
          login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          push ${{ env.IMAGE_NAME }}:${{ env.VERSION }}